version: "3.5"

services:
  redis:
    image: redis:latest
    networks:
      - redisnet

  django_wsgi:
    container_name: django_wsgi
    build: .
    command: uwsgi --socket=:9000 --module=core.wsgi:application --py-autoreload=1
    volumes:
      - .:/code
    networks:
      - webnet
      - redisnet
    links:
      - redis

  django_asgi:
    container_name: django_asgi
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    volumes:
      - .:/code
    networks:
      - webnet
      - redisnet
    links:
      - redis

  nginx:
    image: nginx:1.15.0
    depends_on:
      - django_asgi
      - django_wsgi
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
    networks:
      - webnet
    ports:
      - "80:80"

networks:
  webnet:
  redisnet:
